### ISSUE TITLE
seems legit

### ISSUE THREAD

**Issue by w1zeman1p** [saikatbhadra/do-anything#1]
I really like using any.do so I'm all for making big beautiful todo lists. i'm wondering what cool UI/UX stuff you can add to this, and have it not end up being trello?

**Comment by saikatbhadra** [comment]
I've listed out some ideas here: 

### UI Ideas
* Smart Instant Search / Add?
* TaskDetail
    - Inline Title Editing (click to edit)
    - Sexy Date Selector
    - Undo design pattern (instead of ugly modal) for deleting tasks
* ListDetail
    - Inline Title Editing (click to edit)
    - Swipe right to complete (a la Mailbox)
    - Hover/touch to get more options (add due date, add notes, delete)
    - Completed Lists
    - Archive View
* ListIndex
    - Animation to update badge count for number of remaining due tasks     
    - Inline Title Editing (click to edit)
    - Hover/touch to get more options (publish, archive)
    - Completed Lists
    - Archive View
