### ISSUE TITLE
public lists

### ISSUE THREAD

**Issue by w1zeman1p** [saikatbhadra/do-anything#2]
I'm not familiar with wunderlist, I'm guessing they have something about public lists? What is this feature and why is it cool?

**Comment by saikatbhadra** [comment]
I'm not sure if its cool but I figured I could build a sexy browse page showing lost of cool todos like:
* work out your abs
* Learn git
* Find a rails developer
This would be kinda fun for an employer to browse (and allow them to quickly get started without typing stuff in. Here's an example of the feature in Wunderlist (I don't think it's used much):
https://www.wunderlist.com/list/129908846

I'll let you decide if its cool. You can imagine the browse page  to look something like this:
* https://ifttt.com/recipes/hot
(Screenshot if you don't use IFTTT: 
https://www.dropbox.com/s/6ja8r89q80ebnau/Screenshot%202015-02-02%2016.42.07.png?dl=0)

I'd probably scrap this if the sexy UI stuff takes a long time (i.e. I'd prioritize a nice UI over this).

**FYI**
I wanted to originally build a public collaborative list with no auth across the app at all (i.e. something that anyone can edit &  see updates real time kinda like Doodle.com) but I don't think that will be feasible given my level of knowledge right now. I wouldn't know how to trigger the views to update on other collaborators without constantly polling. I think without the real time updating on each of the user pages it would kinda suck so I scrapped this idea.

**Comment by w1zeman1p** [comment]
Doing the real time list collaboratively is a good stretch goal for you. Not unreasonable. Checkout pusher.
