### ISSUE TITLE
focus on ui

### ISSUE THREAD

**Issue by jeffnv** [saikatbhadra/do-anything#3]
simple concept of a TODO list would benefit form awesome UI. Everything should react when hovered over and marking things done should be a visual delight. Any do has those awesome rolling check marks, make sure you have plenty of that stuff.

**Comment by saikatbhadra** [comment]
Yep, I've added a section on UI ideas on the readme. Here they are:

### UI Ideas
* Smart Instant Search / Add?
* TaskDetail
    - Inline Title Editing (click to edit)
    - Sexy Date Selector
    - Undo design pattern (instead of ugly modal) for deleting tasks
* ListDetail
    - Inline Title Editing (click to edit)
    - Swipe right to complete (a la Mailbox)
    - Hover/touch to get more options (add due date, add notes, delete)
    - Completed Lists
    - Archive View
* ListIndex
    - Animation to update badge count for number of remaining due tasks     
    - Inline Title Editing (click to edit)
    - Hover/touch to get more options (publish, archive)
    - Completed Lists
    - Archive View
